services:
  payment-wallet-db:
    image: postgres:16.2-alpine
    container_name: payment-wallet-db
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: payment-wallet
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "55432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: redis-cache
    ports:
      - "56379:6379"